package com.finfotechp2p.eligibility;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eligibilityModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	private java.lang.String product_id;
	private java.lang.Boolean isEligible;
	private java.lang.String status;

	public eligibilityModel() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getProduct_id() {
		return this.product_id;
	}

	public void setProduct_id(java.lang.String product_id) {
		this.product_id = product_id;
	}

	public java.lang.Boolean getIsEligible() {
		return this.isEligible;
	}

	public void setIsEligible(java.lang.Boolean isEligible) {
		this.isEligible = isEligible;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public eligibilityModel(java.lang.Integer age, java.lang.String product_id,
			java.lang.Boolean isEligible, java.lang.String status) {
		this.age = age;
		this.product_id = product_id;
		this.isEligible = isEligible;
		this.status = status;
	}

}